Optimized install procedure on Mac OSX

diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -88,3 +88,60 @@ package_exists() {
     return 1
 }
 
+# Install via homebrew
+# $@ - components
+install_cask_on_mac() {
+
+    e_header "Checking status of desired Homebrew formulae (cask) ..."
+    local list_formulae
+    local -a missing_formulae
+    local -a desired_formulae=(
+        $@
+    )
+
+    for index in ${!desired_formulae[*]}
+    do
+        if ! formula_cask_exists ${desired_formulae[$index]}; then
+            # Store the name (and options) of every missing formula
+            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
+        fi
+    done
+
+    if [[ "$missing_formulae" ]]; then
+        # Convert the array of missing formula into a list of space-separate strings
+        list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+
+        e_header "Installing missing Homebrew formulae (cask) ..."
+        # Install all missing formulae
+        brew cask install $list_formulae
+    fi
+}
+
+# Install via homebrew
+# $@ - components
+install_on_mac() {
+
+    e_header "Checking status of desired Homebrew formulae ..."
+    local list_formulae
+    local -a missing_formulae
+    local -a desired_formulae=(
+        $@
+    )
+
+    for index in ${!desired_formulae[*]}
+    do
+        if ! formula_exists ${desired_formulae[$index]}; then
+            # Store the name (and options) of every missing formula
+            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
+        fi
+    done
+
+    if [[ "$missing_formulae" ]]; then
+        # Convert the array of missing formula into a list of space-separate strings
+        list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+
+        e_header "Installing missing Homebrew formulae ..."
+        # Install all missing formulae
+        brew install $list_formulae
+    fi
+}
